// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "serj_bibox@mail.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/v1/auth/login"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "запрос на авторизацию",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.InsertResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/v1/auth/register"
                ],
                "summary": "Создаёт новую запись в таблице friend_user",
                "parameters": [
                    {
                        "description": "регистрация карточки пользователя",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.InsertResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/v1/user"
                ],
                "summary": "Получает запись из таблицы friend_user по ID записи в query parameter",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "friend_user PRIMARY KEY ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrResponse": {
            "description": "Структура HTTP ответа ERROR",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "handlers.InsertResponse": {
            "description": "Структура HTTP ответа метода POST /v1/auth/register",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "handlers.UserResponse": {
            "type": "object",
            "properties": {
                "birth": {
                    "type": "string",
                    "example": "2000-07-28"
                },
                "email": {
                    "type": "string",
                    "example": "anastasia.a.krasnova@gmail.com"
                },
                "login": {
                    "type": "string",
                    "example": "rubella19"
                },
                "name": {
                    "type": "string",
                    "example": "Анастасия"
                },
                "phone": {
                    "type": "string",
                    "example": "+79167003020"
                },
                "tg": {
                    "type": "string",
                    "example": "@Rubella19"
                }
            }
        },
        "model.User": {
            "description": "Структура карточки пользователя в теле запроса POST /v1/auth/register",
            "type": "object",
            "properties": {
                "birth": {
                    "type": "string",
                    "example": "2000-07-28"
                },
                "email": {
                    "type": "string",
                    "example": "anastasia.a.krasnova@gmail.com"
                },
                "id": {
                    "type": "string",
                    "example": "11234"
                },
                "login": {
                    "type": "string",
                    "example": "rubella19"
                },
                "name": {
                    "type": "string",
                    "example": "Анастасия"
                },
                "password": {
                    "type": "string",
                    "example": "1Qwerty!"
                },
                "phone": {
                    "type": "string",
                    "example": "+79167003020"
                },
                "tg": {
                    "type": "string",
                    "example": "@Rubella19"
                }
            }
        },
        "model.UserLogin": {
            "description": "Структура JSON метода POST /v1/auth/login",
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "rubella19"
                },
                "password": {
                    "type": "string",
                    "example": "1Qwerty!"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API для платформы ДРУГ",
	Description:      "API для взаимодействия с сервером платформы ДРУГ.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
